### PR TITLE
[129] Make isReadExternalStoragePermissionsRequired visible in Java

### LINKED ISSUE #129: [BUG] - should isReadExternalStoragePermissionsRequired be marked @JvmStatic
- Lib Version [e.g. 1.1.0] 3.1.0
 
**Describe the bug**
When porting to 3.1.0 from 2.2.2, I found that I could no longer access isReadExternalStoragePermissionsRequired.  I believe this should be a static function.  Can you please add usage of this function to the sample code?

**To Reproduce**
1. Add the following code to your Java project "if (CropImage.isReadExternalStoragePermissionsRequired(getContext(), imageUri))"
2. Rebuild using 3.1.0
3. See compile error

**Expected behavior**
Should compile correctly or have a sample which shows to new usage.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11

**Additional context**
Building using Android Studio 4.2.0

### PR DESCRIPTION
**Pull request by gwharvey**
_Add the issue linked to this PR_
close #129 - https://github.com/CanHub/Android-Image-Cropper/issues/129

# Template 2 [Bug]
### Cause:
Missing JvmStatic annotation

### Reproduce
In java, the following code does not compile: if (CropImage.isReadExternalStoragePermissionsRequired(getContext(), imageUri))

### How the bug was solved:
Added missing annotation

### CODE REVIEW

File: cropper/src/main/java/com/canhub/cropper/CropImage.kt [hunk 1]
```diff
@@ -157,6 +157,7 @@ object CropImage {
      * @param context used to access Android APIs, like content resolve, it is your
      * activity/fragment/widget.
      */
+    @JvmStatic
     fun getPickImageChooserIntent(context: Context): Intent {
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/CropImage.kt:161]: It is possible we add this method usage on the Java sample code? Just wanna be sure no one change it and break in the future =)

File: cropper/src/main/java/com/canhub/cropper/CropImage.kt [hunk 2]
```diff
@@ -177,6 +178,7 @@ object CropImage {
      * @param includeDocuments if to include KitKat documents activity containing all sources
      * @param includeCamera    if to include camera intents
      */
+    @JvmStatic
     fun getPickImageChooserIntent(
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/CropImage.kt:182]: It is possible we add this method usage on the Java sample code? Just wanna be sure no one change it and break in the future =)

File: CHANGELOG.md [hunk 3]
```diff
@@ -10,6 +10,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 - `Security` in case of vulnerabilities.
 
 ## [unreleased x.x.x] -
+### Fixed
+- Cannot call library method from Java language [#129](https://github.com/CanHub/Android-Image-Cropper/issues/129)
```
Comment (Canato) [inline CHANGELOG.md:14]: Let's be a little more specific here, for documentation history. Could use the PR name `Make isReadExternalStoragePermissionsRequired visible in Java` I know we have two more methods with it, but not an issue

**Review by Canato — CHANGES_REQUESTED** [review]
Great work! looking forward to release it today. Just some questions

File: cropper/src/main/java/com/canhub/cropper/CropImage.kt (hunk 1 above)
Comment (gwharvey) [reply cropper/src/main/java/com/canhub/cropper/CropImage.kt:161]: I am not sure how you want this done within the current sample code.  I think a better approach would be for you to add it to the Kotlin sample code in a way that it can also be added to the Java sample code.  That said, I am not sure that it is important to have both variants of  getPickImageChooserIntent in the sample code.

File: cropper/src/main/java/com/canhub/cropper/CropImage.kt (hunk 2 above)
Comment (gwharvey) [reply cropper/src/main/java/com/canhub/cropper/CropImage.kt:182]: Done.  Java sample matches Kotlin sample

File: CHANGELOG.md (hunk 3 above)
Comment (gwharvey) [reply CHANGELOG.md:14]: Done.  In my defense, I just re-used the comment from line 21 ;)

Comment (Canato) [reply CHANGELOG.md]: We are always improving ^^, don't feel the need to defend yourself hahaha. I make some mistakes cause no one like to review my PRs ;'( 

Still looking for people to help more =)

**Review by Canato — APPROVED** [review]
Nice Work! Will be released on Monday when I can be paying more attention
