### PR TITLE
fixed the bug that Gallery picker option is not showing

### LINKED ISSUE #20: Gallery option is not showing
Screenshot_2020-12-21-19-41-11-983_android

Android 10 

Using Android Studio 3.6.3

I followed the steps as given but only camera and file options show up in the intent . The gallery option is not visible.I am also using the latest version of the library.

### PR DESCRIPTION
**Pull request by datdescartes**
close #20 #52

### Cause:
Wrong Intent for gallery

### Reproduce
please refer #20 
```
val intent = CropImage.activity()
    .setCropShape(CropImageView.CropShape.RECTANGLE)
    .setAspectRatio(1, 1)
    .setFixAspectRatio(true)
    .setGuidelines(CropImageView.Guidelines.ON)
    .setCropMenuCropButtonTitle("OK")
    .getIntent(this)
startActivityForResult(intent, 123)
```

### How the bug was solved:
Copy [the code from legacy lib](https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImage.java#L192)

### CODE REVIEW

**Review by kaustubhkp — APPROVED** [review]

File: cropper/src/main/java/com/canhub/cropper/CropImage.java [hunk 1]
```diff
@@ -210,7 +210,13 @@ public static Intent getPickImageChooserIntent(
             allIntents.addAll(getCameraIntents(context, packageManager));
         }
 
-        allIntents.add(getGalleryIntent(Intent.ACTION_GET_CONTENT, includeDocuments));
+        List<Intent> galleryIntents =
+                getGalleryIntents(packageManager, Intent.ACTION_GET_CONTENT, includeDocuments);
+        if (galleryIntents.size() == 0) {
+            // if no intents found for get-content try pick intent action (Huawei P9).
+            galleryIntents = getGalleryIntents(packageManager, Intent.ACTION_PICK, includeDocuments);
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/CropImage.java:217]: What is the Huawei P9 issue? could you pointed me to some information or show the test you did?

File: cropper/src/main/java/com/canhub/cropper/CropImage.java [hunk 2]
```diff
@@ -275,17 +281,40 @@ public static Intent getCameraIntent(@NonNull Context context, Uri outputFileUri
...
+                if (intent
+                        .getComponent()
+                        .getClassName()
+                        .equals("com.android.documentsui.DocumentsActivity")) {
+                    intents.remove(intent);
+                    break;
+                }
+            }
+        }
+        return intents;
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/CropImage.java:317]: This code was changed because of the problem we have on latest OS 29 (when no legacy storage is enable) and 30. Android's 10 and 11 changed the storage access from external into scope storage. Bringing the old code back will bring a know issue back.

did you had the opportunity to test the library in the latests OS?

**Review by Canato — CHANGES_REQUESTED** [review]
Thanks for the PR! really happy to see more people putting hands on to improve the library

I just worry cause this code was changed in #5 to fix another issue. And we need to be sure we didn't bought this problem back.

Could you point me of the tests/devices/OSs you did? 

@ravindu1024 @akkie2016 could take a look and check if the issue returned on this version?

File: cropper/src/main/java/com/canhub/cropper/CropImage.java (hunk 1 above)
Comment (datdescartes) [reply cropper/src/main/java/com/canhub/cropper/CropImage.java:217]: Honestly, I have no idea about that. I have never used a huawei device. Just the code from the legacy lib.

File: cropper/src/main/java/com/canhub/cropper/CropImage.java (hunk 2 above)
Comment (datdescartes) [reply cropper/src/main/java/com/canhub/cropper/CropImage.java:317]: oh. I see. I am using Pixel 4 with android 11 and have no problem with this code.

Didn't notice about #5. I will try to test more and let you know.

**Comment by datdescartes** [comment]
@Canato  I have found that Android 11[ requires permission ](https://developer.android.com/about/versions/11/privacy/package-visibility)to get package info.

I've updated the PR that combines the fixes in #5 and the legacy code with permission fixed.
The huawei line is removed as getGalleryIntents() always return notEmpty-list.

Tested in Android 11(pixel 4) and Android 7(Xperia)

**Comment by Canato** [comment]
Nice work! 

Some bits, please update the `CHANGELOG` with
```
### Fixed
- [Galley option not showing](https://github.com/CanHub/Android-Image-Cropper/issues/20)
- [Camera option not showing](https://github.com/CanHub/Android-Image-Cropper/issues/52)
```

And remove the `#20` comments, uncommenting the related code.
- `CropImage.java` line 156 `// TODO Issue #20` 
- `fragment_main.xml` line 48 `<!--  Todo Issue #20  -->` and uncomment the code
-  `CropImageViewFragment` line 75 `// TODO Issue #20` and uncomment the code.


 ## My Test
 Running the sample app, after uncomment the above, if I click the image search I cannot see the galley option 
photo5846150917873841738

Pixel 3, Android 11

Are you hitting something similar? or is working for you? Could provide some video/screen if is working? Maybe is my device issue and I can check

**Comment by Canato** [comment]
@datdescartes

**Comment by datdescartes** [comment]
@kaustubhkp  Sorry, I don't have pixel 4 in my hand now. Will try it on weekend.
It seems the android [Q's bug that only shows up maximum 2 items.](https://issuetracker.google.com/issues/134367295)

I have added the workaround, could you test if it works.

File: cropper/src/main/java/com/canhub/cropper/CropImage.java [hunk 3]
```diff
@@ -272,20 +265,54 @@ public static Intent getCameraIntent(@NonNull Context context, Uri outputFileUri
...
+    public static List<Intent> getGalleryIntents(
+            @NonNull PackageManager packageManager, String action, boolean includeDocuments) {
+        List<Intent> intents = new ArrayList<>();
+        Intent galleryIntent = new Intent(action);
         galleryIntent.setType(includeDocuments ? "*/*" : "image/*");
         galleryIntent.addCategory(Intent.CATEGORY_OPENABLE);
 
-        return galleryIntent;
+        List<ResolveInfo> listGallery = packageManager.queryIntentActivities(galleryIntent, 0);
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && listGallery.size() > 2) {
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/CropImage.java:289]: Please change `Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q` to `CommonVersionCheck.INSTANCE.isAtLeastQ29()`

**Review by Canato — CHANGES_REQUESTED** [review]
Very nice! now is working like a charm for me!

Great add to the library @datdescartes 


To merge we just need to polish some bits

##  1. Please update the `CHANGELOG` with
```
### Fixed
- [Galley option not showing](https://github.com/CanHub/Android-Image-Cropper/issues/20)
- [Camera option not showing](https://github.com/CanHub/Android-Image-Cropper/issues/52)
```

## 2. Remove the `#20` comments, uncommenting the related code.
- `CropImage.java` line 156 `// TODO Issue #20` 
- `fragment_main.xml` line 48 `<!--  Todo Issue #20  -->` and uncomment the code
-  `CropImageViewFragment` line 75 `// TODO Issue #20` and uncomment the code.

## 3. Use the `CommonVersionCheck` class
- change `Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q` to `CommonVersionCheck.INSTANCE.isAtLeastQ29()`


## Question:
On my test (using the sample app) after choosing a image from camera/gallery the image do not load into the screen.
I would say this is a sample bug that I need to fix later, not related to your changes and out of the scope of this PR.
But can you confirm me that you was able to load a image from camera/gallery on your tests?

**Comment by datdescartes** [comment]
Hi @Canato 
I've just done the 1,2,3 above.
I have also [fixed the sample bug](https://github.com/CanHub/Android-Image-Cropper/pull/53/commits/45352c28d1fc7acd293e6cded4be5b6ba22e12db). Confirmed that the image from picker show on screen. (Using fixed sample app)

**Comment by kaustubhkp** [comment]
@datdescartes Awesome Job...

I did some testing on Google Pixel 4 XL device and it works like charm for me

Now It shows camera, Gallery and Files option for me...I verified after cropping image it sending data inside onActivityResult as well :)

screenshot

**Review by Canato — APPROVED** [review]
Solid amazing work! 

If you are feeling so, join us as team member =)
https://github.com/CanHub/Android-Image-Cropper/discussions/42

Next release coming!
