### PR TITLE
Do not crop after pick cancelled

### LINKED ISSUE #162: [BUG] - Camera crop image activity is not removed
- Lib Version: 3.2.1

[youtube video](https://www.youtube.com/watch?v=ODZDNa7Gkr4)

## Steps to reproduce the behaviour:

1. Open Camera
2. Capture a Image
1. Crop a image 
1. Open crop selector again
1. Don't select any image
1. return

Cropping photos from the gallery will not result in this. 
this bug appears when after cropping with the camera .

After cropping with the camera, if you do not select an image from the gallery, the camera image result will continue to appear.

### Actual Behaviour:
You can see your first cropped image

### Expected behaviour:
You should close crop activity because you don't have a image selected

### PR DESCRIPTION
**Pull request by tikitu**
close #162 

### Cause:
After cropping a file is left on the file system for later use. The picker contract doesn't respect cancellation, so if it finds that file it will (incorrectly) return it for cropping even though the user intended to _cancel_ file selection.

### Reproduce
1. Open Camera
2. Capture a Image
3. Crop a image
4. Open crop selector again
5. Don't select any image
6. return

### How the bug was solved:
Discussion on #162 suggested removing the file after cropping. However it seems to me that we can't know when to do this safely: because we return a URI to this file, we can't know whether the library's client has finished using it or not. Instead I made the picker contract explicitly respect cancellation: when cancelled, it returns no URI even if there is a file available.

### CODE REVIEW

**Comment by tikitu** [comment]
The test is rather low-level, but I believe I've confirmed using the Sample app that this indeed solves the user-level problem.

**Comment by Canato** [comment]
This PR is beauty 🤩 

Will check later today/tomorrow.

File: cropper/src/main/java/com/canhub/cropper/PickImageContract.kt [hunk 1]
```diff
@@ -37,6 +38,10 @@ open class PickImageContract : ActivityResultContract<Boolean, Uri?>() {
         resultCode: Int,
         intent: Intent?
     ): Uri? {
+        if (resultCode == Activity.RESULT_CANCELED) {
+            context = null
+            return null
+        }
```
Comment (Canato) [inline cropper/src/main/java/com/canhub/cropper/PickImageContract.kt:44]: Small refactor

```kt
 ): Uri? =
     when(resultCode) {
         is Activity.RESULT_CANCELED -> {
             context = null
             return null
         }
         else -> {
             context?.let {
                 context = null
                 getPickImageResultUriContent(it, intent)
             }
         }
     }    
```

**Review by Canato — CHANGES_REQUESTED** [review]

**Review by Canato — APPROVED** [review]
